"""
Aggregate token-level Integrated Gradients attribution outputs across seeds.

This script assumes that attribution files have already been generated by
interpretability/run_attribution.py for each seed.

Expected input structure, by default:

    output_interpretability_multiseed/
    ├── seed_0/
    │   └── integrated_gradients_token_attributions_clean.csv
    ├── seed_1/
    │   └── integrated_gradients_token_attributions_clean.csv
    └── ...

It produces:
    1. Per-seed token aggregation files
    2. A combined token-occurrence file across seeds
    3. A cross-seed token summary
    4. Filtered summaries using minimum count / minimum sample thresholds
    5. Optional attribution-vs-log-odds summaries if labels are available

Important:
    Integrated Gradients scores are token-occurrence-level scores.
    This script aggregates them into word/token-type-level summaries.
    These summaries are descriptive, not causal clinical markers.
"""

import argparse
import glob
import os
import re
from pathlib import Path
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd


DEFAULT_EXCLUDE_TOKENS = {
    "",
    " ",
    "[cls]",
    "[sep]",
    "[pad]",
    "[mask]",
    "<s>",
    "</s>",
    "<pad>",
    "<mask>",
}


def normalize_token(token: object, lowercase: bool = True) -> str:
    """Normalize a token for aggregation."""
    tok = str(token).strip()

    # Remove common WordPiece prefix.
    tok = tok.replace("##", "")

    # Normalize whitespace.
    tok = re.sub(r"\s+", " ", tok)

    if lowercase:
        tok = tok.lower()

    return tok


def is_punctuation_only(token: str) -> bool:
    """Return True if token contains no alphanumeric characters."""
    return not bool(re.search(r"[A-Za-z0-9]", token))


def find_attribution_file(seed_dir: Path, filename: str) -> Optional[Path]:
    """Find one attribution file under a seed directory."""
    direct = seed_dir / filename
    if direct.exists():
        return direct

    matches = sorted(seed_dir.rglob(filename))
    if len(matches) == 0:
        return None

    return matches[-1]


def infer_seed_from_path(path: Path) -> Optional[int]:
    """Infer seed number from a path containing seed_<n>."""
    match = re.search(r"seed_(\d+)", str(path))
    if match:
        return int(match.group(1))
    return None


def standardize_columns(df: pd.DataFrame) -> pd.DataFrame:
    """
    Standardize expected column names.

    Expected columns from run_attribution.py are usually:
        id, label, pred_label, probability_dementia,
        token_position, token, attribution, abs_attribution,
        is_reportable_token, convergence_delta
    """
    df = df.copy()

    # Common fallbacks.
    rename_map = {}

    if "tokens" in df.columns and "token" not in df.columns:
        rename_map["tokens"] = "token"

    if "attr_score" in df.columns and "attribution" not in df.columns:
        rename_map["attr_score"] = "attribution"

    if "sample_id" in df.columns and "id" not in df.columns:
        rename_map["sample_id"] = "id"

    df = df.rename(columns=rename_map)

    required = {"token", "attribution"}
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"Attribution file is missing required columns: {sorted(missing)}. "
            f"Available columns: {df.columns.tolist()}"
        )

    if "abs_attribution" not in df.columns:
        df["abs_attribution"] = df["attribution"].abs()

    if "id" not in df.columns:
        df["id"] = "unknown_sample"

    return df


def clean_rows(
    df: pd.DataFrame,
    lowercase: bool = True,
    remove_punctuation_only: bool = True,
    exclude_tokens: Optional[set] = None,
) -> pd.DataFrame:
    """Add normalized token column and remove non-reportable rows."""
    if exclude_tokens is None:
        exclude_tokens = DEFAULT_EXCLUDE_TOKENS

    df = df.copy()
    df = standardize_columns(df)

    df["token_norm"] = df["token"].apply(lambda x: normalize_token(x, lowercase=lowercase))

    # Coerce attribution columns.
    df["attribution"] = pd.to_numeric(df["attribution"], errors="coerce")
    df["abs_attribution"] = pd.to_numeric(df["abs_attribution"], errors="coerce")
    df = df.dropna(subset=["attribution", "abs_attribution"])

    # Keep only reportable tokens if the file has this flag.
    if "is_reportable_token" in df.columns:
        df = df[df["is_reportable_token"].astype(bool)]

    # Exclude known special tokens.
    df = df[~df["token_norm"].isin(exclude_tokens)]

    if remove_punctuation_only:
        df = df[~df["token_norm"].apply(is_punctuation_only)]

    return df


def aggregate_token_level(df: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate token-occurrence attributions into token-type summaries.
    """
    group_cols = ["token_norm"]

    agg_dict = {
        "count": ("attribution", "size"),
        "mean_attribution": ("attribution", "mean"),
        "median_attribution": ("attribution", "median"),
        "std_attribution": ("attribution", "std"),
        "min_attribution": ("attribution", "min"),
        "max_attribution": ("attribution", "max"),
        "mean_abs_attribution": ("abs_attribution", "mean"),
        "median_abs_attribution": ("abs_attribution", "median"),
        "max_abs_attribution": ("abs_attribution", "max"),
        "n_samples": ("id", "nunique"),
    }

    if "label" in df.columns:
        agg_dict.update(
            {
                "n_healthy_occurrences": (
                    "label",
                    lambda x: int((pd.to_numeric(x, errors="coerce") == 0).sum()),
                ),
                "n_dementia_occurrences": (
                    "label",
                    lambda x: int((pd.to_numeric(x, errors="coerce") == 1).sum()),
                ),
            }
        )

    if "pred_label" in df.columns:
        agg_dict.update(
            {
                "n_pred_healthy_occurrences": (
                    "pred_label",
                    lambda x: int((pd.to_numeric(x, errors="coerce") == 0).sum()),
                ),
                "n_pred_dementia_occurrences": (
                    "pred_label",
                    lambda x: int((pd.to_numeric(x, errors="coerce") == 1).sum()),
                ),
            }
        )

    if "convergence_delta" in df.columns:
        agg_dict.update(
            {
                "mean_convergence_delta": ("convergence_delta", "mean"),
                "median_convergence_delta": ("convergence_delta", "median"),
            }
        )

    summary = df.groupby(group_cols).agg(**agg_dict).reset_index()

    # Fill std for singletons.
    if "std_attribution" in summary.columns:
        summary["std_attribution"] = summary["std_attribution"].fillna(0.0)

    # Helpful direction labels.
    summary["mean_direction"] = np.where(
        summary["mean_attribution"] > 0,
        "toward_dementia",
        np.where(summary["mean_attribution"] < 0, "away_from_dementia", "near_zero"),
    )

    return summary


def add_log_odds(
    token_summary: pd.DataFrame,
    alpha: float = 1.0,
) -> pd.DataFrame:
    """
    Add smoothed log odds ratio:
        log P(token | dementia) / P(token | healthy)

    Requires n_healthy_occurrences and n_dementia_occurrences.
    """
    required = {"n_healthy_occurrences", "n_dementia_occurrences"}
    if not required.issubset(token_summary.columns):
        return token_summary

    out = token_summary.copy()

    total_healthy = out["n_healthy_occurrences"].sum()
    total_dementia = out["n_dementia_occurrences"].sum()
    vocab_size = len(out)

    out["p_token_given_healthy"] = (
        (out["n_healthy_occurrences"] + alpha)
        / (total_healthy + alpha * vocab_size)
    )
    out["p_token_given_dementia"] = (
        (out["n_dementia_occurrences"] + alpha)
        / (total_dementia + alpha * vocab_size)
    )

    out["log_odds_dementia_vs_healthy"] = np.log(
        out["p_token_given_dementia"] / out["p_token_given_healthy"]
    )

    return out


def add_cross_seed_summary(combined_seed_summaries: pd.DataFrame) -> pd.DataFrame:
    """
    Aggregate per-seed token summaries into cross-seed token summaries.

    This tells us whether token-level attribution tendencies are stable
    across random seeds.
    """
    df = combined_seed_summaries.copy()

    summary = (
        df.groupby("token_norm")
        .agg(
            n_seeds=("seed", "nunique"),
            total_count=("count", "sum"),
            mean_count_per_seed=("count", "mean"),
            total_n_samples=("n_samples", "sum"),
            mean_n_samples_per_seed=("n_samples", "mean"),
            mean_of_seed_mean_attribution=("mean_attribution", "mean"),
            std_of_seed_mean_attribution=("mean_attribution", "std"),
            median_of_seed_mean_attribution=("mean_attribution", "median"),
            mean_of_seed_median_attribution=("median_attribution", "mean"),
            mean_of_seed_mean_abs_attribution=("mean_abs_attribution", "mean"),
            std_of_seed_mean_abs_attribution=("mean_abs_attribution", "std"),
            max_abs_attribution_across_seeds=("max_abs_attribution", "max"),
        )
        .reset_index()
    )

    summary["std_of_seed_mean_attribution"] = summary[
        "std_of_seed_mean_attribution"
    ].fillna(0.0)
    summary["std_of_seed_mean_abs_attribution"] = summary[
        "std_of_seed_mean_abs_attribution"
    ].fillna(0.0)

    summary["cross_seed_direction"] = np.where(
        summary["mean_of_seed_mean_attribution"] > 0,
        "toward_dementia",
        np.where(
            summary["mean_of_seed_mean_attribution"] < 0,
            "away_from_dementia",
            "near_zero",
        ),
    )

    return summary


def save_ranked_tables(
    df: pd.DataFrame,
    output_dir: Path,
    prefix: str,
    mean_col: str,
    abs_col: str,
    min_count_col: str,
    min_count: int,
    min_samples_col: str,
    min_samples: int,
    min_seeds: Optional[int] = None,
) -> Dict[str, Path]:
    """
    Save ranked positive, negative, and absolute attribution tables.
    """
    filtered = df.copy()

    filtered = filtered[
        (filtered[min_count_col] >= min_count)
        & (filtered[min_samples_col] >= min_samples)
    ]

    if min_seeds is not None and "n_seeds" in filtered.columns:
        filtered = filtered[filtered["n_seeds"] >= min_seeds]

    paths = {}

    filtered_path = output_dir / f"{prefix}_filtered_count{min_count}_samples{min_samples}.csv"
    filtered.to_csv(filtered_path, index=False)
    paths["filtered"] = filtered_path

    positive = filtered.sort_values(mean_col, ascending=False)
    negative = filtered.sort_values(mean_col, ascending=True)
    absolute = filtered.sort_values(abs_col, ascending=False)

    positive_path = output_dir / f"{prefix}_top_positive_mean_attribution.csv"
    negative_path = output_dir / f"{prefix}_top_negative_mean_attribution.csv"
    absolute_path = output_dir / f"{prefix}_top_mean_abs_attribution.csv"

    positive.to_csv(positive_path, index=False)
    negative.to_csv(negative_path, index=False)
    absolute.to_csv(absolute_path, index=False)

    paths["top_positive"] = positive_path
    paths["top_negative"] = negative_path
    paths["top_absolute"] = absolute_path

    return paths


def print_top_tables(
    df: pd.DataFrame,
    title: str,
    mean_col: str,
    abs_col: str,
    count_col: str,
    sample_col: str,
    n: int = 20,
) -> None:
    """Print compact top tables."""
    cols = [
        "token_norm",
        count_col,
        sample_col,
        mean_col,
        abs_col,
    ]

    extra_cols = [
        "n_seeds",
        "std_of_seed_mean_attribution",
        "log_odds_dementia_vs_healthy",
        "n_healthy_occurrences",
        "n_dementia_occurrences",
    ]

    for col in extra_cols:
        if col in df.columns and col not in cols:
            cols.append(col)

    cols = [c for c in cols if c in df.columns]

    print(f"\n===== {title}: top positive mean attribution =====")
    print(df.sort_values(mean_col, ascending=False).head(n)[cols].to_string(index=False))

    print(f"\n===== {title}: top negative mean attribution =====")
    print(df.sort_values(mean_col, ascending=True).head(n)[cols].to_string(index=False))

    print(f"\n===== {title}: top mean absolute attribution =====")
    print(df.sort_values(abs_col, ascending=False).head(n)[cols].to_string(index=False))


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Aggregate saved Integrated Gradients token attribution outputs."
    )

    parser.add_argument(
        "--interp_root",
        type=str,
        default="./output_interpretability_multiseed",
        help="Root directory containing seed_<n> attribution outputs.",
    )
    parser.add_argument(
        "--output_dir",
        type=str,
        default="./output_interpretability_multiseed_summary/attribution_aggregated",
        help="Directory where aggregated attribution summaries will be saved.",
    )
    parser.add_argument(
        "--seeds",
        type=str,
        default="0,1,2,3,4",
        help="Comma-separated seed IDs to aggregate.",
    )
    parser.add_argument(
        "--filename",
        type=str,
        default="integrated_gradients_token_attributions_clean.csv",
        help="Attribution filename to search for under each seed directory.",
    )
    parser.add_argument(
        "--min_count",
        type=int,
        default=10,
        help="Minimum total token occurrences for main filtered tables.",
    )
    parser.add_argument(
        "--min_samples",
        type=int,
        default=5,
        help="Minimum number of unique transcripts/samples for main filtered tables.",
    )
    parser.add_argument(
        "--min_seeds",
        type=int,
        default=1,
        help="Minimum number of seeds a token must appear in for cross-seed filtered tables.",
    )
    parser.add_argument(
        "--loose_min_count",
        type=int,
        default=5,
        help="Loose/exploratory minimum total token occurrences.",
    )
    parser.add_argument(
        "--loose_min_samples",
        type=int,
        default=3,
        help="Loose/exploratory minimum unique transcripts/samples.",
    )
    parser.add_argument(
        "--lowercase",
        action="store_true",
        default=True,
        help="Lowercase tokens before aggregation.",
    )
    parser.add_argument(
        "--keep_punctuation",
        action="store_true",
        help="Keep punctuation-only tokens. Default removes them.",
    )
    parser.add_argument(
        "--log_odds_alpha",
        type=float,
        default=1.0,
        help="Smoothing alpha for log odds calculation.",
    )

    args = parser.parse_args()

    interp_root = Path(args.interp_root)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    seeds = [int(s.strip()) for s in args.seeds.split(",") if s.strip()]

    all_occurrence_dfs: List[pd.DataFrame] = []
    all_seed_summary_dfs: List[pd.DataFrame] = []

    per_seed_dir = output_dir / "per_seed"
    per_seed_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading attribution files from: {interp_root}")
    print(f"Saving outputs to: {output_dir}")

    for seed in seeds:
        seed_dir = interp_root / f"seed_{seed}"

        if not seed_dir.exists():
            print(f"Warning: missing seed directory: {seed_dir}")
            continue

        attr_file = find_attribution_file(seed_dir, args.filename)

        if attr_file is None:
            print(f"Warning: missing attribution file for seed {seed}: {args.filename}")
            continue

        print(f"Seed {seed}: {attr_file}")

        df = pd.read_csv(attr_file)
        df = clean_rows(
            df,
            lowercase=args.lowercase,
            remove_punctuation_only=not args.keep_punctuation,
        )
        df["seed"] = seed

        all_occurrence_dfs.append(df)

        seed_summary = aggregate_token_level(df)
        seed_summary = add_log_odds(seed_summary, alpha=args.log_odds_alpha)
        seed_summary["seed"] = seed

        # Move seed column near front.
        cols = ["seed"] + [c for c in seed_summary.columns if c != "seed"]
        seed_summary = seed_summary[cols]

        all_seed_summary_dfs.append(seed_summary)

        seed_summary_path = per_seed_dir / f"seed_{seed}_token_attribution_summary.csv"
        seed_summary.to_csv(seed_summary_path, index=False)

        # Main threshold per-seed ranked files.
        seed_rank_dir = per_seed_dir / f"seed_{seed}_ranked"
        seed_rank_dir.mkdir(parents=True, exist_ok=True)

        save_ranked_tables(
            df=seed_summary,
            output_dir=seed_rank_dir,
            prefix=f"seed_{seed}_main",
            mean_col="mean_attribution",
            abs_col="mean_abs_attribution",
            min_count_col="count",
            min_count=args.min_count,
            min_samples_col="n_samples",
            min_samples=args.min_samples,
        )

        save_ranked_tables(
            df=seed_summary,
            output_dir=seed_rank_dir,
            prefix=f"seed_{seed}_loose",
            mean_col="mean_attribution",
            abs_col="mean_abs_attribution",
            min_count_col="count",
            min_count=args.loose_min_count,
            min_samples_col="n_samples",
            min_samples=args.loose_min_samples,
        )

    if not all_occurrence_dfs:
        raise SystemExit("No attribution files found. Nothing to aggregate.")

    combined_occurrences = pd.concat(all_occurrence_dfs, ignore_index=True)
    combined_seed_summaries = pd.concat(all_seed_summary_dfs, ignore_index=True)

    combined_occurrences_path = output_dir / "all_seed_token_occurrences.csv"
    combined_seed_summaries_path = output_dir / "all_seed_token_summaries_per_seed.csv"

    combined_occurrences.to_csv(combined_occurrences_path, index=False)
    combined_seed_summaries.to_csv(combined_seed_summaries_path, index=False)

    # Aggregate all token occurrences directly across all seeds.
    pooled_summary = aggregate_token_level(combined_occurrences)
    pooled_summary = add_log_odds(pooled_summary, alpha=args.log_odds_alpha)
    pooled_summary_path = output_dir / "pooled_token_attribution_summary.csv"
    pooled_summary.to_csv(pooled_summary_path, index=False)

    # Aggregate per-seed summaries into cross-seed stability summary.
    cross_seed_summary = add_cross_seed_summary(combined_seed_summaries)
    cross_seed_summary_path = output_dir / "cross_seed_token_attribution_summary.csv"
    cross_seed_summary.to_csv(cross_seed_summary_path, index=False)

    # Save ranked pooled tables.
    pooled_rank_dir = output_dir / "pooled_ranked"
    pooled_rank_dir.mkdir(parents=True, exist_ok=True)

    pooled_main_paths = save_ranked_tables(
        df=pooled_summary,
        output_dir=pooled_rank_dir,
        prefix="pooled_main",
        mean_col="mean_attribution",
        abs_col="mean_abs_attribution",
        min_count_col="count",
        min_count=args.min_count,
        min_samples_col="n_samples",
        min_samples=args.min_samples,
    )

    pooled_loose_paths = save_ranked_tables(
        df=pooled_summary,
        output_dir=pooled_rank_dir,
        prefix="pooled_loose",
        mean_col="mean_attribution",
        abs_col="mean_abs_attribution",
        min_count_col="count",
        min_count=args.loose_min_count,
        min_samples_col="n_samples",
        min_samples=args.loose_min_samples,
    )

    # Save ranked cross-seed tables.
    cross_seed_rank_dir = output_dir / "cross_seed_ranked"
    cross_seed_rank_dir.mkdir(parents=True, exist_ok=True)

    cross_seed_main_paths = save_ranked_tables(
        df=cross_seed_summary,
        output_dir=cross_seed_rank_dir,
        prefix="cross_seed_main",
        mean_col="mean_of_seed_mean_attribution",
        abs_col="mean_of_seed_mean_abs_attribution",
        min_count_col="total_count",
        min_count=args.min_count,
        min_samples_col="mean_n_samples_per_seed",
        min_samples=args.min_samples,
        min_seeds=args.min_seeds,
    )

    cross_seed_loose_paths = save_ranked_tables(
        df=cross_seed_summary,
        output_dir=cross_seed_rank_dir,
        prefix="cross_seed_loose",
        mean_col="mean_of_seed_mean_attribution",
        abs_col="mean_of_seed_mean_abs_attribution",
        min_count_col="total_count",
        min_count=args.loose_min_count,
        min_samples_col="mean_n_samples_per_seed",
        min_samples=args.loose_min_samples,
        min_seeds=args.min_seeds,
    )

    # Print useful diagnostics.
    print("\nSaved main files:")
    print(f"  {combined_occurrences_path}")
    print(f"  {combined_seed_summaries_path}")
    print(f"  {pooled_summary_path}")
    print(f"  {cross_seed_summary_path}")

    print("\nPooled main ranked files:")
    for name, path in pooled_main_paths.items():
        print(f"  {name}: {path}")

    print("\nCross-seed main ranked files:")
    for name, path in cross_seed_main_paths.items():
        print(f"  {name}: {path}")

    print("\nDataset summary:")
    print(f"  Seeds found: {sorted(combined_occurrences['seed'].unique().tolist())}")
    print(f"  Token occurrences: {len(combined_occurrences)}")
    print(f"  Unique normalized tokens: {combined_occurrences['token_norm'].nunique()}")
    print(f"  Unique samples: {combined_occurrences['id'].nunique()}")

    if "label" in combined_occurrences.columns:
        print("\nLabel counts over token occurrences:")
        print(combined_occurrences["label"].value_counts(dropna=False).to_string())

    # Print compact main-threshold tables from pooled summary.
    pooled_main_filtered = pd.read_csv(pooled_main_paths["filtered"])
    print_top_tables(
        pooled_main_filtered,
        title=f"Pooled tokens, count>={args.min_count}, samples>={args.min_samples}",
        mean_col="mean_attribution",
        abs_col="mean_abs_attribution",
        count_col="count",
        sample_col="n_samples",
        n=20,
    )

    cross_seed_main_filtered = pd.read_csv(cross_seed_main_paths["filtered"])
    print_top_tables(
        cross_seed_main_filtered,
        title=(
            f"Cross-seed tokens, total_count>={args.min_count}, "
            f"mean_samples>={args.min_samples}, seeds>={args.min_seeds}"
        ),
        mean_col="mean_of_seed_mean_attribution",
        abs_col="mean_of_seed_mean_abs_attribution",
        count_col="total_count",
        sample_col="mean_n_samples_per_seed",
        n=20,
    )


if __name__ == "__main__":
    main()
